// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXIy1Zj4Z7s-4qWj_pqttsPOKWpZlvoU',
    appId: '1:155438760432:android:82f0727da868e495f2dd35',
    messagingSenderId: '155438760432',
    projectId: 'gateease-23400',
    storageBucket: 'gateease-23400.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDolL4Xr4TjyDLP_HWw2BsW3_XWdioERo',
    appId: '1:155438760432:ios:ef8a1dfbca3af42df2dd35',
    messagingSenderId: '155438760432',
    projectId: 'gateease-23400',
    storageBucket: 'gateease-23400.firebasestorage.app',
    androidClientId: '155438760432-jes3ipg1uo4p9qvv7bg1m0vdrfcjh6h7.apps.googleusercontent.com',
    iosClientId: '155438760432-uahs0v8c9mn4ej3irg5dn87f8vjpi6l2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gateEase',
  );

}